name: cartpole
monitor_metric: "eval/reward"
offline_only: false
preprocess_on_load: false
env_id: CartPole-v1 # Or custom if needed
num_envs: 4
num_steps: 500
gamma: 0.99
gae_lambda: 0.95

default_plots: [convergence, losses, reports]
