name: cchs
monitor_metric: "val/loss"
env_id: cchs
offline_only: true
preprocess_on_load: false
gamma: 0.99
gae_lambda: 0.95
reward_type: outcome
dataset_name: cchs.npz

default_plots: [losses, reports]
